name: backend deploy

on:
  push:
    paths: 
      - 'server/**'
      - '.github/workflows/backend.yaml'

jobs:
  deploy-backend:
    runs-on: self-hosted
    steps:
      - name: "checkout Code"
        uses: actions/checkout@v3
   
      - name: "Deploy backend via ssh"
        uses: appleboy/ssh-action@master        
        with:
          host: ${{secrets.API_IP}}
          username: ${{secrets.API_USER}}
          key: ${{secrets.EC2_SECRET}}
          script: |
            cd ~/ci_cd_project

            # pull form main

            git pull origin main

            # inject .env

            echo "${{secrets.ENV_FILE}} > .env"


            cd server

            npm ci

            npx prisma migrate deploy || npx prisma db push

            pm2 restart node-app || pm2 start index.js --name node-app

            pm2 save




        