name: backend deploy

on:
  push:
    paths: 
      - 'server/**'
      - '.github/workflows/backend.yaml'

jobs:
  deploy-backend:
    runs-on: self-hosted
    steps:
      - name: "checkout Code"
        uses: actions/checkout@v3
   
      - name: "Install Dependencies"
        working-directory: ./server
        run: |
         npm ci
        
      - name : "Inject .env file"
        working-directory: ./server
        run: |
          echo "${{secrets.ENV_FILE}}" > .env

      - name: "Prisma Migrate Deploy (or db push)"
        working-directory: ./server
        run: npx prisma migrate deploy
      - name: Restart Backend using PM2
        working-directory: ./server
        run: |
          pm2 restart node-app || pm2 start index.js --name node-app
          pm2 save