name: frontend deploy
on:
 push:
  paths:
    - 'client/**'
    - '.github/workflows/frontend.yaml'

jobs:
    deploy-frontend:
        runs-on: self-hosted
        steps:
        - name: "checkout Code"
          uses: actions/checkout@v3


        - name: Inject .env file
          working-directory: ./client
          run: |
           echo "${{ secrets.FRONTEND_ENV_FILE }}" > .env
        
        - name: Install dependencies
          working-directory: ./client
          run: |
            npm ci
        
        - name: Build app
          working-directory: ./client
          run: |
            npm run build

        - name: Archive build files
          run: tar -czf client-dist.tar.gz -C client/dist .

        - name: list built files
          run: ls -R ./client/dist
            
        - name: copy build files to EC2
          uses: appleboy/scp-action@v1
          with:
            host: ${{secrets.EC2_HOST}}
            username: ${{secrets.EC2_USER}}
            key: ${{secrets.EC2_SECRET}}
            source: "client-dist.tar.gz"
            target: "~/"

        
        - name: Extract and deploy on EC2
          uses: appleboy/ssh-action@master
          with:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SECRET }}
           script: |
            sudo mkdir -p /var/www/react-app
            sudo tar -xzf ~/client-dist.tar.gz -C /var/www/react-app
            rm ~/client-dist.tar.gz
            sudo systemctl restart nginx

            