name: frontend deploy
on:
 push:
  paths:
    - 'client/**'
    - '.github/workflows/frontend.yaml'

jobs:
    deploy-frontend:
        runs-on: self-hosted
        steps:
        - name: "checkout Code"
          uses: actions/checkout@v3
        
        - name: Install dependencies
          working-directory: ./client
          run: |
            npm ci
        
        - name: Build app
          working-directory: ./client
          run: |
            npm run build
        - name: list built files
          run: ls -R ./client/dist
            
        - name: copy build files to EC2
          uses: appleboy/scp-action@v1
          with:
            host: ${{secrets.EC2_HOST}}
            username: ${{secrets.EC2_USER}}
            key: ${{secrets.EC2_SECRET}}
            source: "client/dist"
            target: "/var/www/react-app"
            overwrite: true
            debug: true
        
        - name: Move files with sudo to /var/www/react-app
          uses: appleboy/ssh-action@v1
          with:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SECRET }}
           script: |
             sudo rm -rf /var/www/react-app
             sudo mv /home/ubuntu/react-app-temp /var/www/react-app
             sudo chown -R www-data:www-data /var/www/react-app
             sudo chmod -R 755 /var/www/react-app
             sudo systemctl restart nginx

            