name: frontend deploy
on:
 push:
  paths:
    - 'client/**'
    - 'github/workflows/frontend.yaml'

jobs:
    deploy-frontend:
        runs-on: self-hosted
        steps:
        - name: "checkout Code"
          uses: actions/checkout@v3
        
        - name: Install dependencies
          working-directory: ./client
          run: |
            npm ci
        
        - name: Build app
          working-directory: ./client
          run: |
            npm run build
        
            
        - name: copy build files to EC2
          uses: appleboy/scp-action@v1
          with:
            host: ${{secrets.EC2_HOST}}
            username: ${{secrets.EC2_USER}}
            key: ${{secrets.EC2_SECRET}}
            source: "client/build/*"
            target: "/var/www/react-app"
        
        - name: Restart nginx
          uses: appleboy/scp-action@v1
          with:
            host: ${{secrets.EC2_HOST}}
            username: ${{secrets.EC2_USER}}
            key: ${{secrets.EC2_SECRET}}
            script: |
                sudo systemctl restart nginx


            